export const ROUTE_ERROR = "500_ERROR"
export const NO_MORE_CONTACTS_ERROR = "NO_MORE_CONTACTS_ERROR"

export const ROUTES_ERROR_MISSING_BODY_PARAMS = "ROUTES_ERROR_MISSING_BODY_PARAMS"
export const USER_ERROR_LOGIN_FAILED = "USER_ERROR_LOGIN_FAILED"